name = "ProjectBasedDemo"
uuid = "1a566602-ad7c-42d2-967d-2280445e9c07"
authors = ["Frankie Robertson <frankie@robertson.name>"]
version = "0.1.0"

[deps]
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"

[compat]
Oxygen = "1"
