name = "Oxygen"
uuid = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
authors = ["Nathan Ortega <nate.ortega95@gmail.com>"]
version = "1.0.2"

[compat]
julia = "^1.6.6"
HTTP = "^0.9"
JSON3 = "^1.9"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"